In [1]:
# This is the result of my first attempt at scraping the data from the NIL College Athletes website.
# The function outputs a data frame, but it does not scrape data from the other pages and put it in the data frame.
# It also separates each sponsor, so the first 12 sponsors actually belong to the first student listed.
# I'm not sure why it does not scrape data from the rest of the pages, and I'm also not sure why it separates each sponsor. I have a separate loop that separates each individual sponsor shown below.

import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import re
from urllib.parse import urljoin

nilurl= "https://nilcollegeathletes.com/athletes"

def scrapeNIL(nilurl):
    
    #Retrieving the NIL website:
    nilcolathel = requests.get("https://nilcollegeathletes.com/athletes")
    
    #Parsing the website with BeautifulSoup:
    parsed = BeautifulSoup(nilcolathel.text)
    
    #Names:
    nameParsed = [i for i in parsed.find_all('td', class_="px-2 md:px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900")]
    
    #Sponsors:
    sponsorParsed= parsed.find_all('li', class_="text-sm text-gray-900 truncate")
    
    #University and Sport
    b = [i for i in parsed.find_all('span', class_="truncate")]

    #Iterating over all names:
    studNames=[]
    for i in nameParsed:
        #Add the name to the names list:
        studNames.append(i.text.strip())
    studNames=list(studNames)
    studNames= pd.DataFrame(studNames, columns=['Name'])
    #studNames
    
    #Sponsors:     
    sponsors= [i.text.strip().replace('\n', '') for i in sponsorParsed]
    sponsors=list(sponsors)
    sponsors=pd.DataFrame(sponsors,columns=['Sponsor'])
    #sponsors
    
    #University and Sport
    uni= [i.text.strip() for i in b]
    #uni
    
    univ=[]
    sport=[]
    
    # Separating university and sport:
    for i, j in enumerate(uni): #enumerate adds a counter to an iterable and returns it to a form of enumerating object
        if i%2==0: #If the remainder of the element is 0 then it appends the value to the univ list.
            univ.append(j.strip())
        else:
            sport.append(j.strip()) #If the remainder of the element is not 0, then it appends it to the sport list. 
    
    #Creating a data frame with university and sport:
    univ=list(univ)
    sport=list(sport)
    univ= pd.DataFrame(univ, columns=['university'])
    sport= pd.DataFrame(sport, columns=['sport'])
    univSport= univ.join([sport])
    #univSport
    
    #Creating a dataframe
    nilDf= studNames.join([sponsors, univSport])
    
    return nilDf
    
    #Getting data from other pages:
    root='https://nilcollegeathletes.com'
    try:
        nextPage= urljoin(root, parsed.find('div', class_='-mt-px flex w-0 flex-1 justify-end').a['href']) #This joins the root object and the href
    except:
        nextPage= None
    
    #Combining data from other pages (If there is another page of results):
    if nextPage:
        return pd.concat([nilDf, scrapeNIL(nextPage)], axis=0)
    #Otherwise return the current data
    else:
        return nilDf

In [2]:
scrapeNIL("https://nilcollegeathletes.com/athletes")

,Name,Sponsor,university,sport
0,Jashon Hubbard,614 Chiropractic,The Ohio State University,Wrestling
1,Jonathan Shuskey,Barstool Sports,Christian Brothers University,Golf
2,Collin Gillespie,CRMD Ice Cream,Villanova University,Basketball
3,Buddy Boeheim,Celsius,Syracuse University,Basketball
4,Armando Bacot,Chill Cryotherapy,University of North Carolina at Chapel Hill,Basketball
5,Aaron McLaughlin,Essentia Water,North Carolina State University,Football
6,Brevin Galloway,Ez Fresh Meals,Boston College,Basketball
7,Bryce Young,Go Puff,University of Alabama,Football
8,Graham Mertz,Liquid I.V.,University of WisconsinâMadison,Football
9,B.J. Foster,Max Effort Muscle,University of Texas at Austin,Football
10,Deshun Murrell,Playa Bowls,"University of California, Los Angeles",Football
11,Bryan Robinson,Rewild Yoga,Florida State University,Football
12,Angel Reese,Barstool Sports,"University of Maryland, College Park",Basketball
13,D'Eriq King,Liquid I.V.,University of Miami,Football
14,Spencer Rattler,Swing Juice,University of Oklahoma,Football
15,Hanna Cavinder,Talco Industrial Chemicals,"California State University, Fresno",Basketball
16,Haley Cavinder,The Winston Collection,"California State University, Fresno",Basketball
17,Nik Scalzo,Barstool Sports,University of Kentucky,Football
18,Austin Deculus,Outback Steakhouse,Louisiana State University,Football
19,Spencer Lee,Enduraphin,University of Iowa,Wrestling

In [3]:
# Sponsors individually separated:
nilcolathel = requests.get("https://nilcollegeathletes.com/athletes")
parsed = BeautifulSoup(nilcolathel.text)
sponsorParsed_indiv= parsed.find_all('li', class_="text-sm text-gray-900 truncate")

#Sponsors:    
sponsorsIndiv=[]
for i in sponsorParsed_indiv:
    sponsText= i.text.strip()
    sponsorsIndiv.append(sponsText)
sponsorsIndiv= pd.DataFrame(sponsorsIndiv, columns=['sponsors'])

sponsorsIndiv

                      sponsors
0             614 Chiropractic
1              Barstool Sports
2               CRMD Ice Cream
3                      Celsius
4            Chill Cryotherapy
5               Essentia Water
6               Ez Fresh Meals
7                      Go Puff
8                  Liquid I.V.
9            Max Effort Muscle
10                 Playa Bowls
11                 Rewild Yoga
12             Barstool Sports
13                 Liquid I.V.
14                 Swing Juice
15  Talco Industrial Chemicals
16      The Winston Collection
17             Barstool Sports
18          Outback Steakhouse
19                  Enduraphin
20         Three Wishes Cereal
21             Jimmy's Seafood
22             Barstool Sports
23             Barstool Sports
24                    Cash App
25               Raising Canes
26               PSD Underwear
27                    SoHoodie
28               PSD Underwear
29                    SoHoodie
30                    Wrangler
31               PSD Underwear
32                    SoHoodie
33                 Yoke Gaming
34          Outback Steakhouse
35  College Hunks Hauling Junk
36                   The Wharf
37               Raising Canes
38                Boost Mobile
39      Six Star Pro Nutrition
40                Boost Mobile
41      Six Star Pro Nutrition
42             Barstool Sports
43             Barstool Sports
44               PSD Underwear
45                 Yoke Gaming
46             Barstool Sports

In [4]:
#Scraping the actual table from the website (Attempt #2)

parsed = BeautifulSoup(nilcolathel.text, 'lxml') #Obtains the website page information and changes the HTML to lxml.
#parsed

#Obtain information from <table> tag:
table= parsed.find('table', class_="min-w-full divide-y divide-gray-200")
#table

#Create a column list:
# Obtaining all titles of columns with tag <th>
headers = []
for i in table.find_all('th'):
 title = i.text.strip()
 headers.append(title)
headers

# Create the dataframe:
nil_df= pd.DataFrame(columns=headers)
nil_df

# Creating a for loop to fill the dataframe
for i in table.find_all('tr')[1:]: #Locates the rows by finding the <tr> tags
     row_data = i.find_all('td') #Locates the items by finding the <td> tags
     row = [i.text.strip() for i in row_data] #Grabs the text of the items in 'row_data' and puts it in the 'row' object.
     length = len(nil_df) #Takes the number of items of nil_df (which is 5) and puts it in the 'length' object.
     nil_df.loc[length] = row 
    
#nil_df

# Cleaning the dataframe
nil_df.drop(["Details"], inplace=True, axis=1) #Deletes the Details column
nil_df

,Name,Sponsors,University,Sport
0,Jashon Hubbard,614 Chiropractic \n ...,The Ohio State University,Wrestling
1,Jonathan Shuskey,Barstool Sports\n ...,Christian Brothers University,Golf
2,Collin Gillespie,Barstool Sports\n ...,Villanova University,Basketball
3,Buddy Boeheim,Enduraphin\n ...,Syracuse University,Basketball
4,Armando Bacot,Jimmy's Seafood,University of North Carolina at Chapel Hill,Basketball
5,Aaron McLaughlin,Barstool Sports,North Carolina State University,Football
6,Brevin Galloway,Barstool Sports,Boston College,Basketball
7,Bryce Young,Cash App,University of Alabama,Football
8,Graham Mertz,Raising Canes,University of WisconsinâMadison,Football
9,B.J. Foster,PSD Underwear\n ...,University of Texas at Austin,Football
10,Deshun Murrell,PSD Underwear\n ...,"University of California, Los Angeles",Football
11,Bryan Robinson,PSD Underwear\n ...,Florida State University,Football
12,Angel Reese,Outback Steakhouse,"University of Maryland, College Park",Basketball
13,D'Eriq King,College Hunks Hauling Junk\n ...,University of Miami,Football
14,Spencer Rattler,Raising Canes,University of Oklahoma,Football
15,Hanna Cavinder,Boost Mobile\n ...,"California State University, Fresno",Basketball
16,Haley Cavinder,Boost Mobile\n ...,"California State University, Fresno",Basketball
17,Nik Scalzo,Barstool Sports,University of Kentucky,Football
18,Austin Deculus,Barstool Sports\n ...,Louisiana State University,Football
19,Spencer Lee,Barstool Sports,University of Iowa,Wrestling

In [12]:
# Scrapping the On3 NIL 100

nil100url='https://www.on3.com/nil/rankings/player/nil-100/'

# Function that changes the social media and valuation values to floats
def valchange(i):
    if i[-1:] ==  'K':  # Check if the last digit is K
        return float(i[:-1])*1000 # Remove the last digit with [:-1], and convert to int and multiply by 1000
    elif i[-1:] == 'M':  # Check if the last digit is M
        return float(i[:-1])* 1000000 # Remove the last digit with [:-1], and convert to int and multiply by 1000000
    else:  # just in case data doesnt have an M or K
        i= float(i)  # just in case data doesnt have an M or K
        
def scrapeNIL100(nil100url):
    # Retrieving the On3 NIL 100 Page
    nil100= requests.get('https://www.on3.com/nil/rankings/player/nil-100/')

    #Parsing the page with Beautiful Soup
    nil100Parsed= BeautifulSoup(nil100.text)

    # School Level (College or High School)
    schoolLevelparsed= [i for i in nil100Parsed.find_all('h6', class_='MuiTypography-root NilPlayerRankingItem_orgType__jTK2b MuiTypography-subtitle1 MuiTypography-colorTextPrimary')]

    # Athlete's Name
    athleteNameparsed= [i for i in nil100Parsed.find_all('div', class_='NilPlayerRankingItem_nameYearContainer__R16k_')]

    #Rating
    Ratingsparsed= [i for i in nil100Parsed.find_all('span', class_='StarRating_overallRating__MTh52 StarRating_bolded__kr_6V StarRating_border__DffWl')]

    #Status
    statusParsed= [i for i in nil100Parsed.find_all('p', class_='MuiTypography-root NilPlayerRankingItem_statusText__G8SdI MuiTypography-body1 MuiTypography-colorTextPrimary')]
    
    #Social Media Followers
    socMediaparsed= [i for i in nil100Parsed.find_all('p', class_='MuiTypography-root NilPlayerRankingItem_followersNumber__ifWQr MuiTypography-body1 MuiTypography-colorTextPrimary')]
    
    #On3 NIL Valuation
    valParsed= [i for i in nil100Parsed.find_all('p', class_='MuiTypography-root NilPlayerRankingItem_valuationCurrency__oSkvo MuiTypography-body1 MuiTypography-colorTextPrimary')]
    
    # Iterating over the School Level 
    schoolLevel=[]
    for i in schoolLevelparsed:
        schoolLevel.append(i.text.strip())
    schoolLevel= pd.DataFrame(schoolLevel, columns=['school_level'])
    #schoolLevel

    # Iterating over the Athlete's Name
    athleteName=[]
    for i in athleteNameparsed:
        athleteName.append(i.text.strip())
    athleteName= pd.DataFrame(athleteName, columns=['athelete_name'])
    #athleteName
    
    # Combining schoolLevel and athleteName into one data frame:
    col12= schoolLevel.join([athleteName])

    #Iterating over the Ratings
    ratings=[]
    for i in Ratingsparsed:
        ratings.append(i.text.strip())
    ratings= pd.DataFrame(ratings, columns=['ratings'])
    #Ratings
    
    # Adding Ratings to the data frame:
    col123= col12.join([ratings])
    
    # Iterating over the Status 
    status=[]
    for i in statusParsed:
        status.append(i.text.strip())
    status= pd.DataFrame(status, columns=['status'])
    #status
    
    # Adding Status to the data frame:
    col1234= col123.join([status])
    
    # Iterating over Social Media followers
    socialMedia=[]
    for i in socMediaparsed:
        i_soctext= i.text.strip()
        i_socfloat= valchange(i_soctext)
        socialMedia.append(i_socfloat)
    socialMedia= pd.DataFrame(socialMedia, columns=['soc_med_followers'])
    #socialMedia
    
    # Adding socialMedia to the data frame:
    col12345= col1234.join([socialMedia])
    
    # Iterating over On3 NIL Valuation
    valuation=[]
    for i in valParsed:
        i_text= i.text.strip()
        i_nodolla= i_text.replace('$', '')
        i_valfloat= valchange(i_nodolla)
        valuation.append(i_valfloat)
    valuation= pd.DataFrame(valuation, columns=['valuation'])
    #valuation
    
    # Adding valuation to the data frame (final data frame):
    nil100Df= col12345.join([valuation])
    
    return nil100Df

on3nil100= scrapeNIL100('https://www.on3.com/nil/rankings/player/nil-100/')
on3nil100

,school_level,athelete_name,ratings,status,soc_med_followers,valuation
0,H.S.,Bronny James2023,97.11,Commit,12900000.0,6100000.0
1,NCAA,Livvy Dunne2020,98.76,JR,11300000.0,3400000.0
2,NCAA,Caleb Williams2021,99.53,JR,277000.0,2600000.0
3,NCAA,Arch Manning2023,99.56,FR,254000.0,2100000.0
4,NCAA,Travis Hunter2022,89.16,SO,1300000.0,1700000.0
...,...,...,...,...,...,...
95,NCAA,Antwane Wells2019,NaN,NaN,13600.0,518000.0
96,NCAA,Devin Leary2018,NaN,NaN,37000.0,517000.0
97,NCAA,Dwight McGlothern2020,NaN,NaN,31000.0,511000.0
98,H.S.,Dylan Harper2024,NaN,NaN,4400.0,509000.0
99,NCAA,Hailey Van Lith2020,NaN,NaN,837000.0,506000.0

In [14]:
# Multiple Regression of the On3 NIL 100 data with Valuation as the dependent variable:
import statsmodels.formula.api as smf

reg = smf.ols("valuation ~ C(school_level) + C(status) + soc_med_followers", data=on3nil100).fit()
print(reg.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              valuation   R-squared:                       0.655
Model:                            OLS   Adj. R-squared:                  0.616
Method:                 Least Squares   F-statistic:                     17.06
Date:                Wed, 10 May 2023   Prob (F-statistic):           2.07e-15
Time:                        00:16:14   Log-Likelihood:                -1305.2
No. Observations:                  91   AIC:                             2630.
Df Residuals:                      81   BIC:                             2655.
Df Model:                           9
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Intercept                7.494e+05   1.71e+05      4.379      0.000    4.09e+05    1.09e+06
C(school_level)[T.NCAA]  4.692e+04   1.46e+05      0.321      0.749   -2.44e+05    3.38e+05
C(status)[T.FR]          2.691e+05   2.32e+05      1.160      0.249   -1.92e+05    7.31e+05
C(status)[T.JR]         -1.169e+05   1.46e+05     -0.803      0.424   -4.06e+05    1.73e+05
C(status)[T.RS-JR]      -1.465e+05   2.29e+05     -0.639      0.525   -6.02e+05     3.1e+05
C(status)[T.RS-SO]       1.654e+05   2.81e+05      0.588      0.558   -3.94e+05    7.25e+05
C(status)[T.RS-SR]      -2.118e+05   1.88e+05     -1.124      0.264   -5.87e+05    1.63e+05
C(status)[T.SO]         -3.465e+04    1.8e+05     -0.192      0.848   -3.93e+05    3.24e+05
C(status)[T.SR]         -1.157e+05   1.69e+05     -0.684      0.496   -4.52e+05    2.21e+05
soc_med_followers           0.2834      0.024     11.932      0.000       0.236       0.331
==============================================================================
Omnibus:                       47.670   Durbin-Watson:                   1.409
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              191.528
Skew:                           1.649   Prob(JB):                     2.57e-42
Kurtosis:                       9.296   Cond. No.                     1.79e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.79e+07. This might indicate that there are
strong multicollinearity or other numerical problems.